name: Build and test

on:
  pull_request:
  workflow_call:

permissions:
  contents: read
  id-token: write

jobs:
  check:
    strategy:
      matrix:
        target: ["cpu"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Check
        run: cargo check --features ${{ matrix.target }}

  lint:
    strategy:
      matrix:
        target: ["cpu"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy

      - name: Lint
        run: cargo clippy --features ${{ matrix.target }} -- -D warnings

  build:
    strategy:
      matrix:
        target: ["cpu"]
    needs: [check, lint]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release --features ${{ matrix.target }}
