name: Deploy Marble NER API

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: Environment to deploy to
        required: false
      image:
        type: string
        description: Docker image to deploy
        required: true
      version:
        type: string
        description: Docker image version to deploy
        required: true

permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    name: Deploy Marble NER API
    environment: ${{ inputs.environment }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to GCP
        id: auth
        uses: google-github-actions/auth@v2
        with:
          token_format: access_token
          project_id: ${{ vars.GCP_PROJECT_ID }}
          workload_identity_provider: ${{ vars.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ vars.SERVICE_ACCOUNT_EMAIL }}

      - name: Deploy API
        run: |
          gcloud run deploy marble-ner \
            --quiet \
            --image=${{ inputs.image }}:${{ inputs.version }} \
            --region=europe-west1
