name: Deploy to staging

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: ./.github/workflows/build.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: production
      image: europe-west1-docker.pkg.dev/marble-infra/marble/marble-ner:${{ github.ref_name }}
      push: true

  deploy:
    needs: [build]
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: production
      image: europe-west1-docker.pkg.dev/marble-infra/marble/marble-ner:${{ github.ref_name }}
