name: Deploy to production

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"

jobs:
  build:
    uses: ./.github/workflows/build.yml

  docker:
    needs: [build]
    uses: ./.github/workflows/docker.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: production
      image: europe-west1-docker.pkg.dev/marble-infra/marble/marble-ner
      version: ${{ github.sha }}
      push: true

  deploy:
    needs: [docker]
    uses: ./.github/workflows/deploy.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: production
      image: europe-west1-docker.pkg.dev/marble-infra/marble/marble-ner
      version: ${{ github.ref_name }}-cpu
